### ISSUE TITLE
/tmp issue on Windows

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/cli#36]
See [this topic in the forum](https://forum.getkirby.com/t/kirby-cli-cant-install-or-update/6150?u=lukasbestle). The bug was introduced at some point since CLI version 1.5.0.

**Comment by dweidner** [comment]
I am having a similar issue on Mac OS 10.12.2. `kirby install kirby-playground` tries to create a temporary directory at `/tmp//tmp/kirby-getkirby-starterkit-587340cf20229` which fails. `Kirby CLI version 1.6.0`.

**Comment by rmeister** [comment]
Similar issue like for @dweidner, on Ubuntu 16.04, PHP7.

```
$ kirby install:core
Downloading from: https://github.com/getkirby/kirby/archive/master.zip
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 93

Warning: rename(): The first argument to copy() function cannot be a directory in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 93
PHP Warning:  rename(/tmp//tmp/kirby-getkirby-kirby-58c9c54165792/kirby-master/branches,/home/richard/workspace/websites/hog/kirby/branches): Invalid cross-device link in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 93

Warning: rename(/tmp//tmp/kirby-getkirby-kirby-58c9c54165792/kirby-master/branches,/home/richard/workspace/websites/hog/kirby/branches): Invalid cross-device link in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 93

                                
  [RuntimeException]            
  branches could not be copied  
                                

install:core [--dev]
```

I changed the way how $tmp is build in Command.php
```
//$tmp = $this->tmp(preg_replace('!.zip$!', '', $zip));
$tmp = preg_replace('!.zip$!', '', $zip);
```
but that does not help:
```
Warning: rename(): The first argument to copy() function cannot be a directory in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 94
PHP Warning:  rename(/tmp/kirby-getkirby-kirby-58c9cb478f865/kirby-master/branches,/home/richard/workspace/websites/hog/kirby/branches): Invalid cross-device link in /home/richard/.config/composer/vendor/getkirby/cli/src/Command.php on line 94
```

I have no clue about php, but it seems like `rename` is not able to move directories. Changing it to `copy()` also won't help, as it is not able to copy recursively: http://stackoverflow.com/questions/5424150/the-first-argument-to-copy-function-cannot-be-a-directory#5424235

Tried the recursive function from SO and had no luck, but maybe this are some hints for someone who knows php better than me.

**Comment by unsalted** [comment]
Same issue in Debian shows up

I have a docker you can test it in.

https://hub.docker.com/r/unsalted/kirby-apache/

**Comment by bezin** [comment]
Any news on that issue? It is still an ongoing issue. I will be happy to provide more information if needed?

**Comment by bezin** [comment]
I can say that it does not work on my installation because the unzip routine tries to create the temporary folder in "/tmp" where PHP has no write permissions on a regular windows installlation (except with an elevated prompt). If however the temporary folder is created in the kirby root, updating an installation does work.

**Comment by unsalted** [comment]
It's definitely an issue but there hasn't been a commit on this project on a year so it may not be worthwhile to get your hopes up for a fix.  I haven't looked at the pull requests to see if someone else has fixed the problem, I have no intention of doing so because I'm not a PHP ace.

**Comment by strukturart** [comment]
@bastianallgeier  please take a look on this issue, for the moment the kirby cli to not work on linux.

**Comment by rasteiner** [comment]
I've found several problems when trying to install a plugin, 2 of them related to this issue, the other emerges when this issue is fixed:

1. how tempdir is defined. Currently it's [hardcoded as `'/tmp'`](https://github.com/getkirby/cli/blob/master/src/Command.php#L16). This does not work in Windows because `/tmp` as path in Windows is ambiguous (it depends on the current drive when the script is run).
The temp folder path on Windows depends on installation, the current user and the configuration of php. One could use the [sys-get-temp-dir](http://php.net/manual/en/function.sys-get-temp-dir.php) function to correctly determine the location of the system temp folder, but on windows the system temp dir creates all sorts of problems when you try to move stuff out of it to another drive (where the web app might live). Therefore I'd recommend using a path in the current workdir as temp folder. 

2. In `Command::unzip()`, `$tmp` is created as `$tempFolderPath . $tempFolderPath . downloadedZipWithoutZip`. (Notice how the whole path of `$zip` is passed into the `$this->tmp` function, not just the filename). I'd suggest to use the `basename` function to remove both the `.zip` extension as well as the folder path. 

3. `Plugin::fetch()` asks `Command::unzip()` to extract the plugin to the same temp folder created by `Command::unzip()`. Therefore `Command::unzip()` extracts the folder, then moves the "inner branch folder" to the "outher temp folder" and then deletes everything. I'd recommend using another temp folder name for the `Plugin::` stuff. So that we don't have:
   ```txt
   rename "/tmp/<uid>/master" to "/tmp/<uid>", delete "/tmp/<uid>"
   ```
   but 
   ```txt
   rename "/tmp/<uid>/master" to "/tmp/<uid>_master", delete "/tmp/<uid>"
   ```
   the `/tmp/<uid>_master` should afterwards be deleted by `Plugin::cleanUp()`

With these changes made it works (at least on my machine).
