### ISSUE TITLE
[Feature Request] Instal/Update Plugins from Repositories Outside Github

### ISSUE THREAD

**Issue by luxlogica** [getkirby-v2/cli#48]
While Github is popular and provides a great service, there are many competing services that are gaining an increasing number of users, and deserve some love from the Kirby CLI. For instance: **[Gitlab](https://about.gitlab.com)** has gained *a lot* of attention from many private developers, as it offers unlimited private repositories in their FREE account. Other services, like **[Bitbucket](https://bitbucket.org)**, have also lowered their pricing, and started offering (limited) private repos. As a consequence, many small web developers have started moving their repositories to these competing services, in order to keep their client code private - for free, or cheaper. This is the case in my company. 

It seems that the Kirby CLI basically uses Composer to download its packages, so in theory it should be able to pull packages from just about any online-reachable VCS, including [svn](https://subversion.apache.org) and [fossil](http://fossil-scm.org). If that is the case, then perhaps all that is needed is for a **documentation update**, to show users how to instal/update packages from repos outside Github. 

If the Kirby CLI doesn't currently have the option of installing/updating plugins in repositories outside of Github, then perhaps that functionality could be added without too much trouble?

PS - this overlaps with Issue #19.

**Comment by lukasbestle** [comment]
We haven't decided yet on the future of Kirby CLI. We recommend just using Composer to install plugins, so we might discontinue the CLI with Kirby 3. Just to let you know. :)

**Comment by luxlogica** [comment]
OMG, @lukasbestle, I don't know whether to be happy or terrified! I'm guessing a lot of discussion must have taken place about this, and that a decision to kill the CLI would not be taken lightly. I can only hope that the main reason why it's being retired is perhaps because Kirby 3 might already provide us with a way to perform (most of) the functions provided by the CLI?...

If, however, the decision is being made because there are just not enough resources to dedicate to it, then perhaps we could find someone to take over the project, or produce something equivalent/compatible...

**Comment by jenstornell** [comment]
I think it's a good idea to discontinue Kirby CLI, because you can then focus on the most important thing, Kirby.

I have not used Composer that many times, but it's everywhere, so it feels like THE standard way for downloading/updating stuff.

**Maybe these two things could be made:**

1. Put Kirby CLI on a repo with MIT license for anyone to make a fork of. Then I think it could grow fast in many different directions for many different purposes.
2. Educate us in how to use Composer with Kirby for Kirby plugins. Docs, examples (maybe even a video) may be important. Then the swich will be much easier.
